// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.8.0 by WSRD Tencent.
// Generated from `hello.jce'
// **********************************************************************

package Hello

import "bytes"
import "git.code.oa.com/going/gojce"

type GetReq struct {
	Seq int32  `tag:"0"  required:"false"  json:"seq"`
}

// ClassName GetReq
func (_obj *GetReq) ClassName() string{
	return "Hello.GetReq"
}
// ResetDefault GetReq
func (_obj *GetReq) ResetDefault(){
	var empty GetReq
	*_obj = empty
}
// Encode GetReq
func (_obj *GetReq) Encode(buf *bytes.Buffer) error {
	var _err error
	_err = gojce.EncodeTagInt32Value(buf, _obj.Seq, 0)
	if _err != nil {
		return _err
	}
	return nil
}

// Decode GetReq
func (_obj *GetReq) Decode(buf *bytes.Buffer) error{
	var err error
	err = gojce.DecodeTagInt32Value(buf, &_obj.Seq, 0, false)
	if nil != err{
		return err
	}
	return err
}
