// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.8.0 by WSRD Tencent.
// Generated from `hello.jce'
// **********************************************************************

package Hello

import "bytes"
import "git.code.oa.com/going/gojce"

type GetRsp struct {
	Ask int32  `tag:"0"  required:"false"  json:"ask"`
	Label string  `tag:"1"  required:"false"  json:"label"`
}

// ClassName GetRsp
func (_obj *GetRsp) ClassName() string{
	return "Hello.GetRsp"
}
// ResetDefault GetRsp
func (_obj *GetRsp) ResetDefault(){
	var empty GetRsp
	*_obj = empty
}
// Encode GetRsp
func (_obj *GetRsp) Encode(buf *bytes.Buffer) error {
	var _err error
	_err = gojce.EncodeTagInt32Value(buf, _obj.Ask, 0)
	if _err != nil {
		return _err
	}
	_err = gojce.EncodeTagStringValue(buf, _obj.Label, 1)
	if _err != nil {
		return _err
	}
	return nil
}

// Decode GetRsp
func (_obj *GetRsp) Decode(buf *bytes.Buffer) error{
	var err error
	err = gojce.DecodeTagInt32Value(buf, &_obj.Ask, 0, false)
	if nil != err{
		return err
	}
	err = gojce.DecodeTagStringValue(buf, &_obj.Label, 1, false)
	if nil != err{
		return err
	}
	return err
}
